name: Publish latest

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: Budget.CLI 
            asset_name: budgetcli-macos-amd64
          - os: macos-14
            artifact_name: Budget.CLI
            asset_name: budgetcli-macos-arm64
          - os: ubuntu-latest
            artifact_name: Budget.CLI
            asset_name: budgetcli-linux-amd64
          - os: windows-latest
            artifact_name: Budget.CLI.exe
            asset_name: budgetcli-windows-amd64.exe

    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: dotnet publish --output dist/
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
